Repository luna/luna-studio, pull requests merged in 2018-11, with the labels that each got.

#1246 Include imported libraries visualizers in available visualizers #1192
  libs/batch/plugins/luna-empire/src/Empire/Server/Graph.hs
  libs/luna-studio-common/src/LunaStudio/Data/Diff.hs
  libs/luna-studio-common/src/LunaStudio/Data/GUIState.hs
  libs/luna-studio-common/src/LunaStudio/Data/Project.hs
  libs/luna-studio-common/src/LunaStudio/Data/Visualizer.hs
  luna-studio/atom/lib/luna-visualizers.coffee
  luna-studio/node-editor-view/package.yaml
  luna-studio/node-editor-view/src/NodeEditor/Data/Color.hs
  luna-studio/node-editor-view/src/NodeEditor/React/Model/NodeEditor.hs
  luna-studio/node-editor-view/src/NodeEditor/React/Model/Port.hs
  luna-studio/node-editor-view/src/NodeEditor/React/Model/SearcherProperties.hs
  luna-studio/node-editor-view/src/NodeEditor/React/Model/Visualization.hs
  luna-studio/node-editor-view/src/NodeEditor/React/View/Port.hs
  luna-studio/node-editor-view/src/NodeEditor/React/View/Searcher.hs
  luna-studio/node-editor-view/src/NodeEditor/React/View/Sidebar.hs
  luna-studio/node-editor-view/src/NodeEditor/React/View/Visualization.hs
  luna-studio/node-editor/package.yaml
  luna-studio/node-editor/src/JS/Visualizers.hs
  luna-studio/node-editor/src/NodeEditor/Action/Basic/AddNode.hs
  luna-studio/node-editor/src/NodeEditor/Action/Basic/AddPort.hs
  luna-studio/node-editor/src/NodeEditor/Action/Basic/MovePort.hs
  luna-studio/node-editor/src/NodeEditor/Action/Basic/RemovePort.hs
  luna-studio/node-editor/src/NodeEditor/Action/Basic/UpdateCollaboration.hs
  luna-studio/node-editor/src/NodeEditor/Action/Basic/UpdateNode.hs
  luna-studio/node-editor/src/NodeEditor/Action/Basic/UpdateNodeValue.hs
  luna-studio/node-editor/src/NodeEditor/Action/State/NodeEditor.hs
  luna-studio/node-editor/src/NodeEditor/Action/Visualization.hs
  luna-studio/node-editor/src/NodeEditor/Handler/Backend/Graph.hs
Labels: C - Graph Editor, C - IDE, C - Visualisations, D - Intermediate, T - Enhancement

#1250 Bump luna version. Fixes due to refactoring in Luna.
  build-config/backend/stack.yaml
  libs/luna-empire/src/Empire/Commands/Package.hs
Labels: C - IDE, P - High, T - Bug, T - Non-Breaking Change

#1260 Bump luna version to hopefully fix #1254.
  build-config/backend/stack.yaml
Labels: C - IDE, P - Critical, T - Bug, T - Non-Breaking Change

#1266 Bump Luna again to hopefully band-aid fix the windows saving issue
  build-config/backend/stack.yaml
Labels: C - IDE, P - Critical, T - Bug, T - Non-Breaking Change

#1268 Searcher displays functions sorted on usefulness instead of sorting them alphabetically
  build-config/backend/stack.yaml
  libs/batch/plugins/luna-empire/src/Empire/Env.hs
  libs/batch/plugins/luna-empire/src/Empire/Server/Graph.hs
  libs/luna-empire/src/Empire/Commands/Graph.hs
  libs/luna-empire/src/Empire/Empire.hs
  libs/luna-empire/test/EmpireSpec.hs
  libs/luna-studio-common/src/LunaStudio/API/Graph/AddImports.hs
  libs/luna-studio-common/src/LunaStudio/API/Graph/SearchNodes.hs
  libs/luna-studio-common/src/LunaStudio/Data/Diff.hs
  libs/luna-studio-common/src/LunaStudio/Data/GUIState.hs
  libs/luna-studio-common/src/LunaStudio/Data/Graph.hs
  libs/luna-studio-common/src/LunaStudio/Data/NodeLoc.hs
  libs/luna-studio-common/src/LunaStudio/Data/NodeSearcher.hs
  libs/luna-studio-common/src/LunaStudio/Data/Port.hs
  libs/luna-studio-common/src/LunaStudio/Data/PortRef.hs
  libs/luna-studio-common/src/LunaStudio/Data/Searcher/Command.hs
  libs/luna-studio-common/src/LunaStudio/Data/Searcher/Node.hs
  libs/luna-studio-common/src/LunaStudio/Data/TypeRep.hs
  luna-studio/node-editor-view/package.yaml
  luna-studio/node-editor-view/src/NodeEditor/React/Model/NodeEditor.hs
  luna-studio/node-editor-view/src/NodeEditor/React/Model/Searcher.hs
  luna-studio/node-editor-view/src/NodeEditor/React/Model/Searcher/Hint.hs
  luna-studio/node-editor-view/src/NodeEditor/React/Model/Searcher/Input.hs
  luna-studio/node-editor-view/src/NodeEditor/React/Model/Searcher/Mode.hs
  luna-studio/node-editor-view/src/NodeEditor/React/Model/Searcher/Mode/Command.hs
  luna-studio/node-editor-view/src/NodeEditor/React/Model/Searcher/Mode/Node.hs
  luna-studio/node-editor-view/src/NodeEditor/React/Model/SearcherProperties.hs
  luna-studio/node-editor-view/src/NodeEditor/React/View/ExpressionNode.hs
  luna-studio/node-editor-view/src/NodeEditor/React/View/NodeEditor.hs
  luna-studio/node-editor-view/src/NodeEditor/React/View/Searcher.hs
  luna-studio/node-editor-view/src/NodeEditor/React/View/Sidebar.hs
  luna-studio/node-editor/package.yaml
  luna-studio/node-editor/src/NodeEditor/Action/Basic.hs
  luna-studio/node-editor/src/NodeEditor/Action/Basic/CreateGraph.hs
  luna-studio/node-editor/src/NodeEditor/Action/Basic/UpdateNode.hs
  luna-studio/node-editor/src/NodeEditor/Action/Basic/UpdateSearcherHints.hs
  luna-studio/node-editor/src/NodeEditor/Action/Batch.hs
  luna-studio/node-editor/src/NodeEditor/Action/Searcher.hs
  luna-studio/node-editor/src/NodeEditor/Action/State/NodeEditor.hs
  luna-studio/node-editor/src/NodeEditor/Action/Visualization.hs
  luna-studio/node-editor/src/NodeEditor/Batch/Connector/Commands.hs
  luna-studio/node-editor/src/NodeEditor/Handler/Backend/Graph.hs
  luna-studio/node-editor/src/NodeEditor/Handler/Searcher.hs
  luna-studio/node-editor/src/NodeEditor/State/Global.hs
  luna-studio/stack.yaml
Labels: C - IDE, C - UX, D - Intermediate, P - High, T - Enhancement

#1270 Basic heuristic for searcher to figure out if constructor should be added #1209
  luna-studio/node-editor-view/src/NodeEditor/React/Model/Searcher.hs
  luna-studio/node-editor-view/src/NodeEditor/React/Model/Searcher/Hint.hs
  luna-studio/node-editor-view/src/NodeEditor/React/Model/Searcher/Mode.hs
  luna-studio/node-editor-view/src/NodeEditor/React/Model/Searcher/Mode/Node.hs
  luna-studio/node-editor/src/NodeEditor/Action/Searcher.hs
Labels: C - IDE, C - UX, D - Intermediate, P - High, T - Enhancement

#1282 Fix incorrect searcher behaviour while editing name
  luna-studio/node-editor/src/NodeEditor/Action/Basic/UpdateSearcherHints.hs
Labels: C - Graph Editor, C - IDE, C - UX, D - Intermediate, P - Critical, T - Bug
