Repository luna/luna-studio, pull requests merged in 2018-10, with the labels that each got.

#1150 Standard for tests in luna-studio backend
  .stylish-haskell.yaml
  libs/luna-empire/package.yaml
  libs/luna-empire/src/Empire/ASTOps/Builder.hs
  libs/luna-empire/src/Empire/Empire.hs
  libs/luna-empire/test/EmpireSpec.hs
  libs/luna-empire/test/EmpireUtils.hs
  libs/luna-empire/test/FileLoadSpec.hs
  libs/luna-empire/test/FileModuleSpec.hs
  libs/luna-empire/test/MetadataSpec.hs
  libs/luna-empire/test/Test/Graph/PatternMatchSpec.hs
  libs/luna-empire/test/Test/Hspec/Empire.hs
  libs/luna-empire/test/Test/Hspec/Empire/Graph.hs
  libs/luna-empire/test/Test/Hspec/Hspec/WithReason.hs
Labels: D - Intermediate, P - Medium, T - Enhancement

#1165 Fix incorrect ports for pattern match on custom datatype
  libs/luna-empire/package.yaml
  libs/luna-empire/src/Empire/Commands/GraphBuilder.hs
  libs/luna-empire/src/Empire/Commands/Typecheck.hs
  libs/luna-empire/test/EmpireSpec.hs
  libs/luna-empire/test/FileLoadSpec.hs
  libs/luna-empire/test/FileModuleSpec.hs
  libs/luna-empire/test/Main.hs
  libs/luna-empire/test/Spec.hs
  libs/luna-empire/test/Test/Graph/PatternMatchSpec.hs
  libs/luna-empire/test/Test/Hspec/Empire.hs
  libs/luna-empire/test/Test/Typecheck/PatternMatchSpec.hs
Labels: C - Graph Editor, D - Hard, P - High, S - In Progress, T - Bug, T - Enhancement

#1178 Refactor substitute
  libs/batch/plugins/luna-empire/src/Empire/Server/Graph.hs
  libs/luna-empire/src/Empire/Commands/Breadcrumb.hs
  libs/luna-empire/src/Empire/Commands/Graph.hs
  libs/luna-empire/src/Empire/Commands/Graph/Autolayout.hs
  libs/luna-empire/src/Empire/Commands/Graph/Breadcrumb.hs
  libs/luna-empire/src/Empire/Commands/Graph/Code.hs
  libs/luna-empire/src/Empire/Commands/Graph/Context.hs
  libs/luna-empire/src/Empire/Commands/Graph/Metadata.hs
  libs/luna-empire/src/Empire/Commands/Graph/NodeMeta.hs
  libs/luna-empire/src/Empire/Commands/Typecheck.hs
  libs/luna-empire/src/Empire/Data/FileMetadata.hs
  libs/luna-empire/test/CaseSpec.hs
  libs/luna-empire/test/EmpireSpec.hs
  libs/luna-empire/test/EmpireUtils.hs
  libs/luna-empire/test/FileLoadSpec.hs
  libs/luna-empire/test/FileModuleSpec.hs
  libs/luna-empire/test/MetadataSpec.hs
  libs/luna-empire/test/Test/Graph/PatternMatchSpec.hs
  libs/luna-empire/test/Test/Hspec/Empire.hs
  libs/luna-empire/test/Test/Hspec/Empire/Graph.hs
  libs/luna-studio-common/src/LunaStudio/Data/Breadcrumb.hs
  libs/luna-studio-common/src/LunaStudio/Data/GraphLocation.hs
Labels: T - Enhancement

#1217 Rename libraries to match new Luna hash
  build-config/backend/stack.yaml
  libs/luna-empire/package.yaml
Labels: C - External, T - Enhancement, T - Non-Breaking Change
