Repository luna/luna-studio, pull requests merged in 2019-05, with the labels that each got.

#1377 Create a TypeScript Style Guide
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc
  doc/typescript-style-guide.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Beginner, Priority: High, Type: Enhancement

#1376 Replace shelly with typed-process
  runner/package.yaml
  runner/src/StudioRunner.hs
  runner/src/System/Host.hs
  runner/stack.yaml
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Intermediate, Priority: High, Type: Enhancement

#1379 Fix backendLdLibraryPath
  runner/src/StudioRunner.hs
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Beginner, Priority: High, Type: Bug
